feat: adding s3 & cloudfront parsers
lumigo-io/lumigo-node pull request #167
Opened 2020-09-24 15:13 UTC by GuyMoses

2020-09-24 15:14 UTC, GuyMoses commented on src/parsers/eventParser.js
> +  const new_s3_event = {};
I don't know why, but in this page every parser is written in snake-case and not camel-case

2020-09-24 15:29 UTC, efimk-lu commented
@doriaviram & @GuyMoses why not adding ts support for this file? I added it as a request for this ticket. Feasible or not?

2020-09-29 08:22 UTC, uri-p approved these changes

2020-09-29 08:23 UTC, uri-p requested changes

2020-09-29 08:23 UTC, uri-p commented on src/parsers/eventParser.test.js
> +              eTag: '714ee5196a5c0a6e6b9019caa7b6e970',
Should not exists no?

2020-09-29 08:23 UTC, uri-p commented on src/parsers/eventParser.test.js
> +              ownerIdentity: { principalId: 'A2QVTU9T5VMOU3' },
Should not exists no?

2020-09-29 08:23 UTC, uri-p commented on src/parsers/eventParser.test.js
> +              eTag: '714ee5196a5c0a6e6b9019caa7b6e970',
Should not exists no?

2020-09-29 08:24 UTC, GuyMoses commented on src/parsers/eventParser.test.js
> +              eTag: '714ee5196a5c0a6e6b9019caa7b6e970',
it doesn't exist after parsing

2020-09-29 08:24 UTC, GuyMoses commented on src/parsers/eventParser.test.js
> +              eTag: '714ee5196a5c0a6e6b9019caa7b6e970',
it doesn't exist after parsing

2020-09-29 08:25 UTC, GuyMoses commented on src/parsers/eventParser.test.js
> +              ownerIdentity: { principalId: 'A2QVTU9T5VMOU3' },
it doesn't exist after parsing

2020-09-29 08:28 UTC, uri-p approved these changes

2020-09-29 10:13 UTC, doriaviram requested changes

2020-09-29 10:13 UTC, doriaviram commented on src/parsers/eventParser.js
> +    }
You can do util that will help you reuse this?
That gets a JSON and order and return a JSON

2020-10-18 09:15 UTC, doriaviram approved these changes

2020-10-19 11:56 UTC, merged