fix: removeDuplicate implementation
lumigo-io/lumigo-node pull request #285
Opened 2021-06-21 14:20 UTC by saartochner

building the previous implementation was created wrong code:
```
var __spreadArray = (this && this.__spreadArray) || function (to, from) {
    for (var i = 0, il = from.length, j = to.length; i < il; i++, j++)
        to[j] = from[i];
    return to;
};
var removeDuplicates = function (arr) { return __spreadArray([], new Set(arr)); };
```

I replaced this code with a work one and will explore further later.
The attached IT shows that this functionality didn't work before the change and currently works.

2021-06-21 14:37 UTC, saartochner commented
Update: this is the bug:
https://stackoverflow.com/questions/33464504/using-spread-syntax-and-new-set-with-typescript/33464709

2021-06-22 06:01 UTC, doriaviram requested changes

2021-06-22 06:01 UTC, doriaviram commented on src/utils.ts
> -export const removeDuplicates = (arr) => [...new Set(arr)];
Add a test that proves the bug fix

2021-06-22 06:11 UTC, doriaviram approved these changes

2021-06-22 10:24 UTC, merged

2021-06-22 12:27 UTC, doriaviram commented
:tada: This PR is included in version 1.58.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lumigo/tracer/v/1.58.1)
- [GitHub release](https://github.com/lumigo-io/lumigo-node/releases/tag/v1.58.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: