fix: min timeout should be DEFAULT_CONNECTION_TIMEOUT + 50
lumigo-io/lumigo-node pull request #331
Opened 2021-11-29 09:49 UTC by OrrLumigo

2021-11-29 10:42 UTC, doriaviram requested changes

2021-11-29 10:42 UTC, doriaviram commented on src/utils.test.js
> +    expect(utils.getTracerMaxDurationTimeout()).toEqual(350);
Change the timeout of the function to check the 20% logic

2021-11-29 10:42 UTC, doriaviram commented on src/utils.ts
> -    return Math.min(DEFAULT_TRACER_MAX_DURATION_TIMEOUT, remainingTimeInMillis / 5);
Its looks like you deleted this logic, what about small timeout functions?

2021-11-29 10:57 UTC, saartochner commented on src/globals.ts
> +  let lambdaTimeout = DEFAULT_TRACER_TIMEOUT;
maybe "duration" is a better name?

2021-11-29 15:06 UTC, OrrLumigo commented on src/globals.ts
> +  let lambdaTimeout = DEFAULT_TRACER_TIMEOUT;
left or right side ?

2021-11-29 15:29 UTC, doriaviram commented on src/globals.ts
> +        : MAX_TRACER_ADDED_DURATION_ALLOWED,
leave this as undefined, let the user choose how to handle

2021-11-30 07:00 UTC, merged

2021-11-30 09:03 UTC, doriaviram commented
:tada: This PR is included in version 1.66.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lumigo/tracer/v/1.66.4)
- [GitHub release](https://github.com/lumigo-io/lumigo-node/releases/tag/v1.66.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: