Rd 6658 delta missing x amzn trace id error
lumigo-io/lumigo-node pull request #332
Opened 2021-11-29 16:28 UTC by OrrLumigo

2021-11-30 08:25 UTC, doriaviram requested changes

2021-11-30 08:25 UTC, doriaviram commented on src/hooks/http.test.js
> +  spies.awsGuards = jest.spyOn(awsGuards, 'isAwsContext').mockImplementation(() => true);
We want to get rid of spies, why not just use real / un-real context?

2021-11-30 13:25 UTC, nirLumigo approved these changes

2021-11-30 13:35 UTC, doriaviram requested changes
Test

2021-11-30 13:47 UTC, nirLumigo approved these changes

2021-11-30 14:13 UTC, doriaviram approved these changes

2021-11-30 15:20 UTC, merged

2021-12-07 16:20 UTC, doriaviram commented
:tada: This PR is included in version 1.66.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lumigo/tracer/v/1.66.5)
- [GitHub release](https://github.com/lumigo-io/lumigo-node/releases/tag/v1.66.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: