fix: resource name is url and not name
lumigo-io/lumigo-node pull request #348
Opened 2022-01-25 15:55 UTC by OrrLumigo

2022-01-25 16:05 UTC, saartochner commented on src/hooks/http.ts
> +      serviceData = getAwsServiceData({ ...requestData, body }, null);
You better do it in the row below.
You need to use `requestData.body + body` and not only `body`.
Please add test on it

2022-01-25 16:25 UTC, saartochner requested changes
GJ!

2022-01-25 16:56 UTC, doriaviram approved these changes

2022-01-25 17:51 UTC, saartochner approved these changes

2022-01-26 12:46 UTC, merged

2022-01-26 14:49 UTC, doriaviram commented
:tada: This PR is included in version 1.68.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@lumigo/tracer/v/1.68.1)
- [GitHub release](https://github.com/lumigo-io/lumigo-node/releases/tag/v1.68.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: