fix: mysql nested query case
lumigo-io/lumigo-node pull request #375
Opened 2022-05-12 13:02 UTC by doriaviram

2022-05-12 13:04 UTC, doriaviram reviewed
![image](https://user-images.githubusercontent.com/50795205/168081106-f4d80667-5666-4b0a-8427-0f9bbfe8cbec.png)
package.json update

2022-05-15 07:05 UTC, OrrLumigo approved these changes

2022-05-15 11:00 UTC, nirLumigo requested changes
Nice :)

2022-05-15 11:22 UTC, nirLumigo approved these changes

2022-05-17 15:38 UTC, merged